package org.clay.job.db

import org.clay.job.core.po._
import org.clay.job.db.slicks.schema.Tables

package object slicks {
  implicit def jobPo2Row(p:JobPo):Tables.JobsRow = Tables.JobsRow(0,p.uid,
    p.name,
    p.className,
    p.metaData,
    p.dataTimeOffset,
    p.dataTimeOffsetUnit,
    p.startTime,
    p.cron,
    p.priority,
    p.parallel,
    p.retryTimes,
    p.workerNodes,
    p.clusterName,
    p.groupName,
    p.timeout,
    p.replaceIfExist,
    p.lastGenerateTriggerTime,
    p.schedulerNode,
    p.scheduleFrequency,
    p.lastScheduleTime,
    p.updateTime)

  implicit def jobRow2bPo(r:Tables.JobsRow):JobPo = JobPo(r.uid,
    r.name,
    r.className,
    r.metaData,
    r.dataTimeOffset,
    r.dataTimeOffsetUnit,
    r.startTime,
    r.cron,
    r.priority,
    r.parallel,
    r.retryTimes,
    r.workerNodes,
    r.clusterName,
    r.groupName,
    r.timeout,
    r.replaceIfExist,
    r.lastGenerateTriggerTime,
    r.schedulerNode,
    r.scheduleFrequency,
    r.lastScheduleTime,
    r.updateTime)
  implicit def schedulePo2Row(p:SchedulePo):Tables.SchedulesRow = Tables.SchedulesRow(0,p.uid,
    p.jobUid,
    p.priority,
    p.retryTimes,
    p.dispatched,
    p.triggerTime,
    p.scheduleNode,
    p.scheduleTime,
    p.succeed,
    p.dataTime,
    p.updateTime)
  implicit def scheduleRow2Po(r:Tables.SchedulesRow):SchedulePo = SchedulePo(r.uid,
    r.jobUid,
    r.priority,
    r.retryTimes,
    r.dispatched,
    r.triggerTime,
    r.scheduleNode,
    r.scheduleTime,
    r.succeed,
    r.dataTime,
    r.updateTime)
  implicit def taskPo2Row(p:TaskPo):Tables.TasksRow = Tables.TasksRow(0,p.uid,
    p.jobUid,
    p.scheduleUidd,
    p.retryId,
    p.taskTrackerNode,
    p.state,
    p.eventTime,
    p.message,
    p.updateTime)
  implicit def taskRow2Po(r:Tables.TasksRow):TaskPo = TaskPo(r.uid,
    r.jobUid,
    r.scheduleUid,
    r.retryId,
    r.taskTrackerNode,
    r.state,
    r.eventTime,
    r.message,
    r.updateTime)
  implicit def dependencyPo2Row(p:DependencyPo):Tables.DependenciesRow = Tables.DependenciesRow(0,p.uid,
    p.jobUid,
    p.dependJobUid,
    p.timeOffset,
    p.timeOffsetUnit,
    p.timeOffsetMilliSec,
    p.updateTime)
  implicit def dependencyRow2Po(r:Tables.DependenciesRow):DependencyPo = DependencyPo(r.uid,
    r.jobUid,
    r.dependJobUid,
    r.timeOffset,
    r.timeOffsetUnit,
    r.timeOffsetMilliSec,
    r.updateTime)
}
