CREATE TABLE `jobs` (
  `row_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '唯一ID，没有业务含义',
  `uid` varchar(64) NOT NULL COMMENT '作业UID',
  `name` varchar(32) NOT NULL COMMENT 'Job名称，便于区分',
  `class_name` varchar(64) NOT NULL COMMENT 'Job对应的业务类名称',
  `meta_data` json NOT NULL COMMENT '作业传入的静态参数，JSON格式',
  `data_time_offset` bigint(20) NOT NULL COMMENT '作业处理数据的时间偏移量',
  `data_time_offset_unit` varchar(16) NOT NULL COMMENT '作业处理数据的时间偏移量单位',
  `start_time` bigint(20) NOT NULL COMMENT '作业开始调度的时间',
  `cron` varchar(32) NOT NULL COMMENT '作业执行频率，cron表达式',
  `priority` int(11) NOT NULL COMMENT '作业优先级',
  `parallel` int(11) NOT NULL,
  `retry_times` int(11) NOT NULL COMMENT '作业失败重试次数',
  `worker_nodes` varchar(1024) DEFAULT NULL COMMENT '作业执行节点的范围。逗号分隔的IP字符串',
  `cluster_name` varchar(16) NOT NULL COMMENT '作业所属集群。便于划分资源',
  `group_name` varchar(32) NOT NULL COMMENT '作业所属组。逻辑划分，一般指代应用',
  `timeout` int(11) NOT NULL COMMENT '作业超时时间',
  `replace_if_exist` bit(1) NOT NULL COMMENT '作业存在时的行为。true存在则杀掉所有task并更新Job信息；false存在则不进行操作',
  `last_generate_trigger_time` bigint(20) DEFAULT NULL COMMENT '最后一次生成的调度时间',
  `scheduler_node` varchar(64) DEFAULT NULL COMMENT '作业调度器节点',
  `schedule_frequency` bigint(20) DEFAULT NULL COMMENT '调度的周期，即调度器执行的周期，单位是分钟',
  `last_schedule_time` bigint(20) DEFAULT NULL COMMENT '最后一次调度的时间',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录创建时间',
  PRIMARY KEY (`row_id`),
  UNIQUE KEY `UK_NAME` (`name`),
  UNIQUE KEY `UK_JOB_UID` (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='作业表，包含静态信息。只有提交时才能修改';
